apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-dev.yml -o export/
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: user
  name: user
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: user
    spec:
      containers:
      - env:
        - name: APP_SETTINGS
          value: project.config.DevelopmentConfig
        - name: DATABASE_TEST_URL
          value: postgres://postgres:postgres@user-db:5432/user_test
        - name: DATABASE_URL
          value: postgres://postgres:postgres@user-db:5432/user_dev
        - name: FLASK_ENV
          value: development
        image: zhongxilu/user-service:latest
        name: user-service
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
