version: '3.3'

networks:
  mynetwork:
    driver: bridge

services:

  user:
    build:
      context: ./services/user
      dockerfile: Dockerfile-dev
    volumes:
      - './services/user:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@user-db:5432/user_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@user-db:5432/user_test
    depends_on:
      - user-db
    networks:
      - mynetwork

  user-db:
    build:
      context: ./services/user/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork
