version: '3.3'

networks:
  mynetwork:
    driver: bridge

services:

  user:
    container_name: user-service
    image: zhongxilu/user-service:latest
    build:
      context: ./services/user
      dockerfile: Dockerfile-dev
    volumes:
      - './services/user:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@user-db:5432/user_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@user-db:5432/user_test
    depends_on:
      - user-db
    networks:
      - mynetwork

  user-db:
    container_name: user-db
    image: zhongxilu/user-db:latest
    build:
      context: ./services/user/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  order:
    container_name: order-service
    image: zhongxilu/order-service:latest
    build:
      context: ./services/order
      dockerfile: Dockerfile-dev
    volumes:
      - './services/order:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@ticket-db:5432/ticket_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@ticket-db:5432/ticket_test
      - NR_OF_TICKETS=350000
      - TICKETS_PER_SHARD=1000
    depends_on:
      - ticket-db
    networks:
      - mynetwork

  ticket-db:
    container_name: ticket-db
    image: zhongxilu/ticket-db:latest
    build:
      context: ./services/order/project/db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  encryption:
    container_name: encryption-service
    image: zhongxilu/encryption-service:latest
    build:
      context: ./services/encryption
      dockerfile: Dockerfile-dev
    volumes:
      - './services/encryption:/usr/src/app'
    ports:
      - 5003:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@key-db:5432/key_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@key-db:5432/key_test
    depends_on:
      - key-db
    networks:
      - mynetwork

  key-db:
    container_name: key-db
    image: zhongxilu/key-db:latest
    build:
      context: ./services/encryption/project/db
      dockerfile: Dockerfile
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork

  payment:
    container_name: payment-service
    image: zhongxilu/payment-service:latest
    build:
      context: ./services/payment
      dockerfile: Dockerfile-dev
    volumes:
      - './services/payment:/usr/src/app'
    ports:
      - 5004:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - API_RESPONSE_TIME=1.4
    networks:
      - mynetwork
