name: Minikube CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Minikube
      uses: CodingNagger/minikube-setup-action@v1.0.2
    - name: Launch Minikube
      run: sudo minikube start --memory=8192 --cpus=4 --vm-driver=none --kubernetes-version v1.14.6 --extra-config kubeadm.ignore-preflight-errors=SystemVerification
    - name: Set up pods
      run: sudo kubectl create -f export/
    - name: Wait for pods
      uses: jakejarvis/wait-action@master
      with:
        time: '1m'
    - name: Check pods
      run: sudo kubectl get pods
    - name: Run tests
      run: sudo ./runAllTests.sh
    - name: Set up
      run: sudo ./setup.sh

    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install Python packages
      run: pip install requests
    - name: Load test
      run: python test/load_test.py http://$(sudo minikube ip)
